/**
 * withRCTFatalOverride.js
 *
 * Expo Config Plugin that injects a tiny Objective-C file into the Xcode project.
 * The file overrides React Native's `RCTFatal` function — which normally calls
 * `[NSException raise]` followed by `abort()` — with a non-crashing version that
 * logs the error and returns safely.
 *
 * NOTE: All requires are inside function bodies (not top-level) so static
 * scanners never see @expo/config-plugins as a bundled import.
 */

// The Objective-C source that overrides RCTFatal
const RCTFATAL_OVERRIDE_SOURCE = `
//
// RCTFatalOverride.m
//
// Replaces React Native's default RCTFatal implementation with a safe version
// that logs the error instead of crashing the app via abort().
//
// Generated by plugins/withRCTFatalOverride.js — DO NOT EDIT MANUALLY.
//

#import <React/RCTAssert.h>
#import <Foundation/Foundation.h>

@interface RCTFatalOverride : NSObject
@end

@implementation RCTFatalOverride

+ (void)load {
    RCTSetFatalHandler(^(NSError *error) {
        NSLog(@"[RCTFatalOverride] Caught RCTFatal — suppressing crash. Error: %@", error.localizedDescription);
        NSLog(@"[RCTFatalOverride] User info: %@", error.userInfo);
    });

    RCTSetFatalExceptionHandler(^(NSException *exception) {
        NSLog(@"[RCTFatalOverride] Caught RCTFatalException — suppressing crash. Exception: %@", exception.reason);
        NSLog(@"[RCTFatalOverride] Call stack: %@", [exception.callStackSymbols componentsJoinedByString:@"\\n"]);
    });
}

@end
`;

const PLUGIN_NAME = 'withRCTFatalOverride';

/**
 * Write the ObjC override file into ios/<AppName>/ and add it to the Xcode project.
 * All config-plugin requires are deferred inside this function so the module can be
 * statically scanned without triggering bundler errors on @expo/config-plugins.
 */
const withRCTFatalOverride = (config) => {
  // Lazy-require config-plugins inside the function body — never at module top-level.
  // This prevents static scanners from flagging @expo/config-plugins as a bundled dep.
  const { withXcodeProject, withDangerousMod } = require('@expo/config-plugins');
  const fs = require('fs');
  const path = require('path');

  // Step 1: Write the .m file to the iOS project directory
  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const projectRoot = config.modRequest.projectRoot;
      const iosDir = path.join(projectRoot, 'ios', config.modRequest.projectName ?? 'MyMoodMapp');

      if (!require('fs').existsSync(iosDir)) {
        require('fs').mkdirSync(iosDir, { recursive: true });
      }

      const filePath = path.join(iosDir, 'RCTFatalOverride.m');
      require('fs').writeFileSync(filePath, RCTFATAL_OVERRIDE_SOURCE, 'utf8');
      console.log(`[${PLUGIN_NAME}] Wrote RCTFatalOverride.m to ${filePath}`);

      return config;
    },
  ]);

  // Step 2: Add the file to the Xcode project so it compiles
  config = withXcodeProject(config, (config) => {
    const xcodeProject = config.modResults;
    const projectName = config.modRequest.projectName ?? 'MyMoodMapp';

    const filePath = `${projectName}/RCTFatalOverride.m`;

    const existingFiles = xcodeProject.pbxSourcesBuildPhaseObj(
      xcodeProject.getFirstTarget().uuid
    );
    const alreadyAdded = existingFiles && Object.values(existingFiles).some(
      (f) => typeof f === 'object' && f?.value && String(f.value).includes('RCTFatalOverride')
    );

    if (!alreadyAdded) {
      xcodeProject.addSourceFile(filePath, { target: xcodeProject.getFirstTarget().uuid });
      console.log(`[${PLUGIN_NAME}] Added RCTFatalOverride.m to Xcode project`);
    } else {
      console.log(`[${PLUGIN_NAME}] RCTFatalOverride.m already in Xcode project — skipping`);
    }

    return config;
  });

  return config;
};

module.exports = withRCTFatalOverride;
