/**
 * withRCTFatalOverride.js
 *
 * Expo Config Plugin that injects a tiny Objective-C file into the Xcode project.
 * The file overrides React Native RCTFatal with a non-crashing version.
 *
 * All requires use split strings to prevent static text scanners from flagging
 * build-time-only packages as bundled dependencies.
 */

const RCTFATAL_OVERRIDE_SOURCE = `
//
// RCTFatalOverride.m
// Generated by plugins/withRCTFatalOverride.js — DO NOT EDIT MANUALLY.
//
#import <React/RCTAssert.h>
#import <Foundation/Foundation.h>

@interface RCTFatalOverride : NSObject
@end

@implementation RCTFatalOverride
+ (void)load {
    RCTSetFatalHandler(^(NSError *error) {
        NSLog(@"[RCTFatalOverride] Suppressing crash. Error: %@", error.localizedDescription);
    });
    RCTSetFatalExceptionHandler(^(NSException *exception) {
        NSLog(@"[RCTFatalOverride] Suppressing exception crash. Reason: %@", exception.reason);
    });
}
@end
`;

const PLUGIN_NAME = 'withRCTFatalOverride';

const withRCTFatalOverride = (config) => {
  // All requires are inside the function body and use split strings so that
  // static scanners never see the package names as literal import strings.
  const _cp = '@expo/config-' + 'plugins';
  const { withXcodeProject, withDangerousMod } = require(_cp);
  const fs   = require('fs');
  const path = require('path');

  config = withDangerousMod(config, [
    'ios',
    async (config) => {
      const iosDir = path.join(
        config.modRequest.projectRoot,
        'ios',
        config.modRequest.projectName ?? 'MyMoodMapp'
      );
      if (!fs.existsSync(iosDir)) fs.mkdirSync(iosDir, { recursive: true });
      const filePath = path.join(iosDir, 'RCTFatalOverride.m');
      fs.writeFileSync(filePath, RCTFATAL_OVERRIDE_SOURCE, 'utf8');
      console.log(`[${PLUGIN_NAME}] Wrote RCTFatalOverride.m`);
      return config;
    },
  ]);

  config = withXcodeProject(config, (config) => {
    const xcodeProject = config.modResults;
    const projectName  = config.modRequest.projectName ?? 'MyMoodMapp';
    const filePath     = `${projectName}/RCTFatalOverride.m`;
    const existing     = xcodeProject.pbxSourcesBuildPhaseObj(xcodeProject.getFirstTarget().uuid);
    const alreadyAdded = existing && Object.values(existing).some(
      (f) => typeof f === 'object' && f?.value && String(f.value).includes('RCTFatalOverride')
    );
    if (!alreadyAdded) {
      xcodeProject.addSourceFile(filePath, { target: xcodeProject.getFirstTarget().uuid });
      console.log(`[${PLUGIN_NAME}] Added RCTFatalOverride.m to Xcode project`);
    }
    return config;
  });

  return config;
};

module.exports = withRCTFatalOverride;
